services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../app/public/static:/data
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ../app/public/php:/app
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
      - ../data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=php-auth
volumes:
  mysqldata: 